import type { ShortContent, SourceMaterial } from '../../../shared/types';
import { shortLayoutLabels, verificationLabels } from '../../../shared/feeds';
export const blankShort = (): ShortContent => ({ layout:'quote',text:'',context:'',attribution:'',verification:'unverified',sources:[],comparison:[],correction:'' });
export function ShortFields({ value:s, onChange }: { value:ShortContent; onChange:(value:ShortContent)=>void }) {
  function set<K extends keyof ShortContent>(key:K,value:ShortContent[K]){onChange({...s,[key]:value});}
  function source(i:number,patch:Partial<SourceMaterial>){set('sources',s.sources.map((v,n)=>n===i?{...v,...patch}:v));}
  return <div className="short-fields"><div className="form-grid"><label>切片形式<select name="short.layout" value={s.layout} onChange={e=>onChange({...s,layout:e.target.value as ShortContent['layout'],comparison:e.target.value==='comparison'&&s.comparison.length!==2?[{label:'之前',text:'',sourceIndex:null},{label:'之后',text:'',sourceIndex:null}]:s.comparison})}>{Object.entries(shortLayoutLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>核对状态<select name="short.verification" value={s.verification} onChange={e=>set('verification',e.target.value as ShortContent['verification'])}>{Object.entries(verificationLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div>
    {s.layout!=='comparison'&&<label>{s.layout==='quote'?'逐字原话':s.layout==='note'?'行为概述':'图片说明'}<textarea name="short.text" rows={5} maxLength={1600} value={s.text} onChange={e=>set('text',e.target.value)} placeholder="保留原意与必要限定，不用摘要重复一次。"/></label>}
    {s.layout==='image'&&<p className="field-hint">在右侧“条目封面”上传原图，将以完整图片显示，不会裁剪成背景。</p>}
    {s.layout==='comparison'&&<div className="comparison-editor">{s.comparison.map((side,i)=><div key={i}><label>对照 {i+1} 标注<input value={side.label} maxLength={80} onChange={e=>set('comparison',s.comparison.map((v,n)=>n===i?{...v,label:e.target.value}:v))}/></label><label>内容<textarea rows={4} value={side.text} maxLength={800} onChange={e=>set('comparison',s.comparison.map((v,n)=>n===i?{...v,text:e.target.value}:v))}/></label><label>对应来源<select value={side.sourceIndex??''} onChange={e=>set('comparison',s.comparison.map((v,n)=>n===i?{...v,sourceIndex:e.target.value===''?null:Number(e.target.value)}:v))}><option value="">待补充</option>{s.sources.map((v,n)=><option key={n} value={n}>{v.label||`来源 ${n+1}`}</option>)}</select></label></div>)}</div>}
    <label>一句背景<textarea name="short.context" rows={2} maxLength={600} value={s.context} onChange={e=>set('context',e.target.value)} placeholder="发生场景、适用对象、不能省略的前提。"/></label>
    <label>发言者 / 行为主体<input name="short.attribution" maxLength={120} value={s.attribution} onChange={e=>set('attribution',e.target.value)} placeholder="与条目编者分开，仅填写应当公开的信息"/></label>
    <details className="source-editor" open={s.sources.length>0||undefined}><summary>来源材料 <small>{s.sources.length} / 8</small></summary><p className="field-hint">引语、对照与编者概述分开存储。媒体 ID 可从媒体库复制，保存后自动关联附件。</p>
      {s.sources.map((v,i)=><section className="source-editor-row" key={i}><div className="form-grid"><label>材料标题<input value={v.label} maxLength={200} onChange={e=>source(i,{label:e.target.value})}/></label><label>时间标注<input value={v.date} maxLength={40} onChange={e=>source(i,{date:e.target.value})}/></label><label>原始链接<input type="url" value={v.url} maxLength={2048} onChange={e=>source(i,{url:e.target.value})}/></label><label>已上传的媒体 ID<input value={v.mediaId} maxLength={64} onChange={e=>source(i,{mediaId:e.target.value})}/></label></div><label>材料摘录<textarea rows={3} value={v.excerpt} maxLength={3000} onChange={e=>source(i,{excerpt:e.target.value})}/></label><button type="button" className="text-button" onClick={()=>onChange({...s,sources:s.sources.filter((_,n)=>n!==i),comparison:s.comparison.map(c=>({...c,sourceIndex:c.sourceIndex===i?null:c.sourceIndex!==null&&c.sourceIndex>i?c.sourceIndex-1:c.sourceIndex}))})}>移除这份材料</button></section>)}
      <button type="button" className="secondary-button" disabled={s.sources.length>=8} onClick={()=>set('sources',[...s.sources,{label:'',url:'',mediaId:'',excerpt:'',date:''}])}>+ 添加来源</button>
    </details>
    <label>公开更正说明<textarea rows={2} value={s.correction} maxLength={2000} onChange={e=>set('correction',e.target.value)} placeholder="仅有更正时填写"/></label>
  </div>;
}
